x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 10M

services:
  server:
    image: judge0/judge0:1.13.1
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    ports:
      - "0.0.0.0:2358:2358"
    privileged: true
    <<: *default-logging
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M

  workers:
    image: judge0/judge0:1.13.1
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    environment:
      - JUDGE0_WORKERS=1
    <<: *default-logging
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G # Python necesita un poco más de aire para no crashear

  db:
    image: postgres:16.2
    env_file: judge0.conf # Usamos el mismo archivo que el server para que hablen el mismo idioma
    volumes:
      - data:/var/lib/postgresql/data/
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M

  redis:
    image: redis:7.2.4 # Quitamos Alpine porque necesitamos 'bash' para el entrypoint
    command: [
      "redis-server", "--appendonly", "no" # Simplificamos el arranque
    ]
    <<: *default-logging
    restart: always
    deploy:
      resources:
        limits:
          memory: 128M

volumes:
  data: