-- Clean up existing paths for these courses
DELETE FROM learning_path_steps WHERE curso_id IN (1201,1104,1301,1102,1303,1103,1202,1101,1203,1302);

-- Insert new paths
INSERT INTO learning_path_steps (curso_id, title, description, duration, order_index, topics, icon) VALUES
(1301, 'Unidad 1: Introducción y Vectores', 'Mediciones, cifras significativas, vectores y operaciones.', '5h', 1, '{Magnitudes físicas, Sistema de unidades, Vectores, Producto escalar y vectorial}', 'ruler'),
(1301, 'Unidad 2: Cinemática', 'Movimiento rectilíneo, curvilíneo y relativo.', '6h', 2, '{MRU, MRUV, Caída libre, Movimiento parabólico, Movimiento circular}', 'activity'),
(1301, 'Unidad 3: Estática', 'Leyes de Newton, equilibrio de partículas y cuerpo rígido.', '7h', 3, '{Leyes de Newton, Diagrama de cuerpo libre, Equilibrio, Momento de una fuerza}', 'anchor'),
(1301, 'Unidad 4: Dinámica', 'Aplicaciones de leyes de Newton y fuerzas.', '7h', 4, '{Fuerza y masa, Dinámica lineal, Dinámica curvilínea}', 'zap'),
(1301, 'Unidad 5: Trabajo y Energía', 'Teoremas de conservación, energía cinética y potencial.', '9h', 5, '{Trabajo, Energía Cinética, Energía Potencial, Conservación de energía}', 'battery-charging'),
(1301, 'Unidad 6: Sistema de Partículas', 'Centro de masa, momento lineal y choques.', '5h', 6, '{Centro de masa, Momento lineal, Impulso, Choques}', 'users'),
(1301, 'Unidad 7: Fluidos', 'Densidad, presión y Principio de Arquímedes.', '5h', 7, '{Densidad, Presión, Principio de Pascal, Principio de Arquímedes}', 'droplet'),
(1301, 'Unidad 8: Vibraciones y Ondas', 'Movimiento armónico simple y ondas sonoras.', '5h', 8, '{Movimiento armónico simple, Péndulo, Ondas, Sonido}', 'radio'),
(1301, 'Unidad 9: Termodinámica', 'Temperatura, calor y leyes de la termodinámica.', '7h', 9, '{Temperatura, Calor, Dilatación, Leyes de la termodinámica}', 'thermometer'),
(1101, 'Semana 1: Introducción', 'Definiciones básicas, lenguajes y algoritmos.', '3h', 1, '{Algoritmos, Lenguajes, C++}', 'terminal'),
(1101, 'Semana 2: Operadores', 'Operadores aritméticos, relacionales y lógicos.', '3h', 2, '{Operadores, Variables}', 'code'),
(1101, 'Semana 3: Proc. Secuenciales', 'Tipos de datos y estructuras secuenciales.', '3h', 3, '{Tipos de datos, Secuencia}', 'arrow-right'),
(1101, 'Semana 4: Est. Selectivas', 'Sentencias if-else y switch.', '3h', 4, '{If-Else, Switch}', 'git-branch'),
(1101, 'Semana 5: Estructura For', 'Bucles con número de repeticiones definido.', '3h', 5, '{Bucle For}', 'repeat'),
(1101, 'Semana 6: Estructura While', 'Bucles con entrada controlada.', '3h', 6, '{Bucle While}', 'rotate-cw'),
(1101, 'Semana 7: Estructura Do While', 'Bucles con salida controlada.', '3h', 7, '{Do While}', 'refresh-ccw'),
(1101, 'Semana 8: Examen Parcial', 'Evaluación parcial.', '2h', 8, '{Examen Parcial}', 'edit-3'),
(1101, 'Semana 9: Vectores', 'Arreglos unidimensionales.', '3h', 9, '{Vectores, Arreglos}', 'list'),
(1101, 'Semana 10: Matrices', 'Arreglos bidimensionales.', '3h', 10, '{Matrices, Arreglos 2D}', 'grid'),
(1101, 'Semana 11: Cadenas', 'Manipulación de textos y strings.', '3h', 11, '{Strings, Cadenas}', 'type'),
(1101, 'Semana 12: Funciones', 'Funciones definidas por el usuario.', '3h', 12, '{Funciones, Ámbito}', 'box'),
(1101, 'Semana 13: Punteros', 'Introducción a punteros.', '3h', 13, '{Punteros, Memoria}', 'cpu'),
(1101, 'Semana 14: Parámetros', 'Paso por valor y por referencia.', '3h', 14, '{Paso por valor, Paso por referencia}', 'sliders'),
(1101, 'Semana 15: Recursividad', 'Funciones recursivas.', '3h', 15, '{Recursividad, Backtracking}', 'corner-down-left'),
(1101, 'Semana 16: Examen Final', 'Evaluación final.', '2h', 16, '{Examen Final}', 'file-text'),
(1201, 'Semana 1: Integral Indefinida', 'Propiedades, integración por sustitución algebraica.', '4h', 1, '{Integral indefinida, Sustitución algebraica, Integración por partes}', 'plus-square'),
(1201, 'Semana 2: Integración Trigonométrica', 'Integrales de funciones trigonométricas e inversas.', '4h', 2, '{Funciones trigonométricas, Sustitución trigonométrica}', 'triangle'),
(1201, 'Semana 3: La Integral Definida', 'Sumas de Riemann y propiedades.', '4h', 3, '{Sumatoria, Suma de Riemann, Área bajo la curva}', 'bar-chart'),
(1201, 'Semana 4: Teoremas Fundamentales', 'Teorema fundamental del cálculo y valor medio.', '4h', 4, '{Teorema Fundamental del Cálculo, Teorema del Valor Medio}', 'book'),
(1201, 'Semana 5: Funciones Trascendentes', 'Logaritmo y exponencial.', '4h', 5, '{Función Logaritmo, Función Exponencial, Derivadas e Integrales}', 'log-in'),
(1201, 'Semana 6: Funciones Hiperbólicas', 'Definición y propiedades.', '4h', 6, '{Funciones Hiperbólicas, Inversas}', 'activity'),
(1201, 'Semana 7: Otras Bases', 'Exponenciales en otras bases y derivación logarítmica.', '4h', 7, '{Bases generales, Derivación logarítmica}', 'code'),
(1201, 'Semana 8: Examen Parcial', 'Evaluación parcial.', '2h', 8, '{Examen Parcial}', 'edit-3'),
(1201, 'Semana 9: Técnicas de Integración I', 'Potencias trigonométricas y fracciones parciales.', '4h', 9, '{Potencias trigonométricas, Fracciones parciales}', 'divide'),
(1201, 'Semana 10: Técnicas de Integración II', 'Funciones racionales de senos y cosenos.', '4h', 10, '{Funciones racionales, Sustitución de Weierstrass}', 'refresh-cw'),
(1201, 'Semana 11: Integrales Impropias', 'Sustituciones de Euler e integrales impropias.', '4h', 11, '{Sustituciones de Euler, Integrales impropias}', 'alert-circle'),
(1201, 'Semana 12: Funciones Gamma y Beta', 'Aplicaciones y funciones especiales.', '4h', 12, '{Función Gamma, Función Beta, Áreas}', 'star'),
(1201, 'Semana 13: Coordenadas Polares', 'Áreas y gráficas en polares.', '4h', 13, '{Coordenadas polares, Áreas en polares, Volumen disco}', 'compass'),
(1201, 'Semana 14: Volúmenes', 'Métodos del anillo y corteza cilíndrica.', '4h', 14, '{Volúmenes de revolución, Corteza cilíndrica}', 'layers'),
(1201, 'Semana 15: Longitud de Arco y Series', 'Aplicaciones físicas y Series de Taylor.', '4h', 15, '{Longitud de arco, Trabajo, Presión, Series de Taylor}', 'trending-up'),
(1201, 'Semana 16: Examen Final', 'Evaluación final.', '2h', 16, '{Examen Final}', 'file-text'),
(1202, 'Unidad 1: Álgebra Matricial', 'Definiciones y operaciones con matrices.', '3h', 1, '{Matrices, Tipos de matrices, Operaciones, Transpuesta}', 'grid'),
(1202, 'Unidad 2: Determinantes', 'Cálculo y propiedades de determinantes.', '3h', 2, '{Determinantes, Cofactores, Propiedades}', 'maximize'),
(1202, 'Unidad 3: Rango e Inversa', 'Operaciones elementales y cálculo de inversa.', '3h', 3, '{Rango, Matriz Inversa, Operaciones elementales}', 'minimize-2'),
(1202, 'Unidad 4: Sistemas de Ecuaciones', 'Solución de sistemas lineales.', '3h', 4, '{Sistemas lineales, Regla de Cramer, Métodos matriciales}', 'list'),
(1202, 'Unidad 5: Geometría en el Espacio', 'Vectores en R3.', '3h', 5, '{Vectores en R3, Producto escalar, Norma}', 'box'),
(1202, 'Unidad 6: Producto Vectorial', 'Proyección y producto vectorial.', '3h', 6, '{Proyección ortogonal, Producto vectorial, Triple producto}', 'crosshair'),
(1202, 'Unidad 7: Independencia Lineal', 'Conceptos de dependencia e independencia.', '3h', 7, '{Independencia lineal, Dependencia lineal}', 'git-branch'),
(1202, 'Unidad 8: Rectas y Planos', 'Ecuaciones de rectas y planos en el espacio.', '3h', 8, '{Rectas en R3, Planos, Intersecciones}', 'map'),
(1202, 'Unidad 9: Espacios Vectoriales', 'Definición y propiedades generales.', '3h', 9, '{Espacios vectoriales, Subespacios, Base, Dimensión}', 'layout'),
(1202, 'Unidad 10: Transformaciones Lineales', 'Definición, núcleo e imagen.', '3h', 10, '{Transformaciones lineales, Núcleo, Imagen}', 'repeat'),
(1202, 'Unidad 11: Rep. Matricial', 'Matriz asociada a una transformación.', '3h', 11, '{Representación matricial, Operadores lineales}', 'monitor'),
(1202, 'Unidad 12: Valores Propios', 'Autovalores y autovectores.', '3h', 12, '{Valores propios, Vectores propios, Diagonalización}', 'target'),
(1202, 'Unidad 13: Diag. Transformaciones', 'Diagonalización de operadores.', '3h', 13, '{Diagonalización de transformaciones, Ortogonalización}', 'sliders'),
(1202, 'Unidad 14: Formas Cuadráticas', 'Aplicación a cónicas y superficies.', '3h', 14, '{Formas cuadráticas, Cónicas, Superficies}', 'circle'),
(1103, 'Capítulo 1: Estequiometría', 'Teoría atómica y cálculos estequiométricos.', '4h', 1, '{Átomo, Mol, Ecuación química, Balance de materia}', 'flask'),
(1103, 'Capítulo 2: Termoquímica', 'Cambios de energía en reacciones.', '4h', 2, '{Entalpía, Ley de Hess, Calor de reacción}', 'flame'),
(1103, 'Capítulo 3: Estructura Atómica', 'Teoría cuántica y tabla periódica.', '8h', 3, '{Teoría cuántica, Configuración electrónica, Tabla periódica}', 'atom'),
(1103, 'Capítulo 4: Enlace Químico', 'Tipos de enlace y propiedades moleculares.', '8h', 4, '{Enlace iónico, Enlace covalente, Geometría molecular, Fuerzas intermoleculares}', 'share-2'),
(1103, 'Capítulo 5: Estados de la Materia', 'Gases, líquidos y sólidos.', '8h', 5, '{Gases ideales, Presión de vapor, Estado sólido, Cristales}', 'package'),
(1103, 'Capítulo 6: Soluciones', 'Propiedades de las disoluciones.', '4h', 6, '{Solubilidad, Concentración, Propiedades coligativas}', 'droplet'),
(1103, 'Capítulo 7: Cinética Química', 'Velocidad de reacción.', '4h', 7, '{Rapidez de reacción, Energía de activación, Catalizadores}', 'clock'),
(1103, 'Capítulo 8: Equilibrio Químico', 'Principio de Le Chatelier y espontaneidad.', '4h', 8, '{Equilibrio químico, Le Chatelier, Energía libre}', 'scales'),
(1103, 'Capítulo 9: Equilibrio Iónico', 'Ácidos, bases y pH.', '4h', 9, '{pH, Ácidos y Bases, Buffer, Hidrólisis}', 'test-tube'),
(1103, 'Capítulo 10: Electroquímica', 'Redox y celdas galvánicas.', '4h', 10, '{Redox, Celdas galvánicas, Electrólisis, Corrosión}', 'battery'),
(1103, 'Capítulo 11: Materiales', 'Metales, aleaciones y polímeros.', '4h', 11, '{Metales, Aleaciones, Polímeros, Aceros}', 'tool'),
(1104, 'Unidad 1: Vectores 2D', 'Sistema de coordenadas y vectores en el plano.', '4h', 1, '{Coordenadas, Vectores R2, Operaciones}', 'move'),
(1104, 'Unidad 2: Producto Escalar', 'Ortogonalidad y proyección.', '4h', 2, '{Producto escalar, Norma, Ortogonalidad}', 'minimize'),
(1104, 'Unidad 3: Proyección y Área', 'Componentes y áreas de polígonos.', '4h', 3, '{Proyección ortogonal, Área de triángulos}', 'triangle'),
(1104, 'Unidad 4: Independencia Lineal', 'Dependencia lineal y división de segmentos.', '4h', 4, '{Independencia lineal, Punto medio}', 'git-commit'),
(1104, 'Unidad 5: La Recta', 'Ecuaciones y propiedades de la recta.', '4h', 5, '{Ecuación de la recta, Pendiente, Distancia punto-recta}', 'minus'),
(1104, 'Unidad 6: Transformación Coordenadas', 'Traslación y rotación de ejes.', '4h', 6, '{Traslación, Rotación}', 'refresh-ccw'),
(1104, 'Unidad 7: La Circunferencia', 'Ecuación y recta tangente.', '4h', 7, '{Circunferencia, Recta tangente}', 'circle'),
(1104, 'Unidad 8: La Parábola', 'Definición, elementos y ecuaciones.', '4h', 8, '{Parábola, Foco, Directriz}', 'wifi'),
(1104, 'Unidad 9: La Elipse', 'Propiedades y ecuaciones.', '4h', 9, '{Elipse, Ejes, Excentricidad}', 'loader'),
(1104, 'Unidad 10: La Hipérbola', 'Asíntotas y ecuaciones.', '4h', 10, '{Hipérbola, Asíntotas}', 'code'),
(1104, 'Unidad 11: Ecuación General 2do Grado', 'Clasificación de cónicas.', '4h', 11, '{Ecuación general, Cónicas}', 'grid'),
(1104, 'Unidad 12: Invariantes', 'Identificación de cónicas por invariantes.', '4h', 12, '{Invariantes, Rotación de cónicas}', 'shield'),
(1302, 'Unidad 1: Sistemas Numéricos', 'Representación de datos y aritmética binaria.', '8h', 1, '{Binario, IEEE 754, Punto flotante}', 'cpu'),
(1302, 'Unidad 2: Lógica Proposicional', 'Métodos de demostración e inducción.', '4h', 2, '{Lógica, Cuantificadores, Inducción}', 'check-square'),
(1302, 'Unidad 3: Relaciones Binarias', 'Relaciones de equivalencia y orden.', '8h', 3, '{Relaciones, Digrafos, Orden parcial, Hasse}', 'git-merge'),
(1302, 'Unidad 4: Grafos', 'Teoría de grafos y trayectorias.', '4h', 4, '{Grafos, Euler, Matriz adyacencia}', 'share'),
(1302, 'Unidad 5: Árboles', 'Árboles binarios y algoritmos de optimización.', '8h', 5, '{Árboles, Huffman, Prim, Kruskal}', 'git-pull-request'),
(1302, 'Unidad 6: Álgebra de Boole', 'Circuitos lógicos y mapas de Karnaugh.', '8h', 6, '{Álgebra Booleana, Compuertas lógicas, Karnaugh}', 'toggle-left'),
(1302, 'Unidad 7: Estructuras Algebraicas', 'Grupos, semigrupos y codificación.', '8h', 7, '{Grupos, Semigrupos, Hammin, Paridad}', 'box'),
(1302, 'Unidad 8: Teoría de Lenguajes', 'Autómatas y máquinas de estado finito.', '4h', 8, '{Lenguajes, Autómatas, Máquinas de estado}', 'terminal'),
(1303, 'Unidad 1: Cálculo Diferencial Vectorial', 'Derivadas parciales, gradientes y optimización.', '16h', 1, '{Derivadas parciales, Gradiente, Multiplicadores de Lagrange, Máximos y Mínimos}', 'layers'),
(1303, 'Unidad 2: Integrales Múltiples', 'Integrales dobles y triples, cambio de variable.', '14h', 2, '{Integrales dobles, Integrales triples, Coordenadas cilíndricas, Coordenadas esféricas}', 'box'),
(1303, 'Unidad 3: Cálculo Vectorial Integral', 'Integrales de línea y superficie, teoremas integrales.', '14h', 3, '{Integral de línea, Teorema de Green, Teorema de Stokes, Teorema de Gauss}', 'globe'),
(1102, 'Semana 1: Lógica y Conjuntos', 'Introducción a la lógica proposicional y teoría de conjuntos.', '4h', 1, '{Lógica Proposicional, Conectivos, Conjuntos}', 'brain'),
(1102, 'Semana 2: Números Reales', 'Sistema de números reales y desigualdades.', '4h', 2, '{Números reales, Desigualdades}', 'hash'),
(1102, 'Semana 3: Valor Absoluto', 'Valor absoluto y máximo entero.', '4h', 3, '{Valor absoluto, Máximo entero}', 'maximize'),
(1102, 'Semana 4: Funciones', 'Dominio, rango y funciones especiales.', '4h', 4, '{Funciones, Dominio, Rango}', 'activity'),
(1102, 'Semana 5: Operaciones Funciones', 'Álgebra y composición de funciones.', '4h', 5, '{Álgebra de funciones, Composición}', 'plus-circle'),
(1102, 'Semana 6: Funciones Inversas', 'Función inversa y propiedades.', '4h', 6, '{Función inversa, Univalente}', 'rotate-ccw'),
(1102, 'Semana 7: Límites', 'Cálculo de límites.', '4h', 7, '{Límites algebraicos, Límites trigonométricos}', 'arrow-right'),
(1102, 'Semana 8: Examen Parcial', 'Evaluación parcial.', '2h', 8, '{Examen Parcial}', 'edit-2'),
(1102, 'Semana 9: Continuidad', 'Continuidad y asíntotas.', '4h', 9, '{Continuidad, Asíntotas}', 'git-commit'),
(1102, 'Semana 10: Teoremas Continuidad', 'Bolzano y Valor Intermedio.', '4h', 10, '{Teorema Valor Intermedio, Bolzano}', 'bookmark'),
(1102, 'Semana 11: La Derivada', 'Definición y reglas de derivación.', '4h', 11, '{Derivada, Regla de la cadena}', 'zap'),
(1102, 'Semana 12: Diferenciabilidad', 'Derivación implícita.', '4h', 12, '{Diferenciabilidad, Derivada implícita}', 'git-pull-request'),
(1102, 'Semana 13: Aplicaciones Derivada', 'Teorema del Valor Medio y Rolle.', '4h', 13, '{Valor Medio, Rolle, Lagrange}', 'trending-up'),
(1102, 'Semana 14: Extremos', 'Máximos y mínimos.', '4h', 14, '{Máximos, Mínimos, Optimización}', 'bar-chart'),
(1102, 'Semana 15: Concavidad', 'L''Hopital y gráficas.', '4h', 15, '{Concavidad, L''Hopital}', 'curve'),
(1102, 'Semana 16: Examen Final', 'Evaluación final.', '2h', 16, '{Examen Final}', 'award'),
(1203, 'Semana 1: Estructuras de Control', 'Secuenciales y selectivas.', '2h', 1, '{Control secuencial, If-Else, Anidamiento}', 'code'),
(1203, 'Semana 2: Estructuras Repetitivas', 'Bucles y repeticiones.', '2h', 2, '{For, While, Do-While}', 'repeat'),
(1203, 'Semana 3: Arreglos', 'Arreglos unidimensionales.', '2h', 3, '{Arrays, Vectores}', 'list'),
(1203, 'Semana 4: Ordenamiento', 'Algoritmos de ordenamiento.', '2h', 4, '{Bubble sort, Selection sort}', 'bar-chart-2'),
(1203, 'Semana 5: Búsqueda', 'Algoritmos de búsqueda.', '2h', 5, '{Búsqueda lineal, Búsqueda binaria}', 'search'),
(1203, 'Semana 6: Matrices', 'Arreglos multidimensionales.', '2h', 6, '{Matrices 2D, Operaciones matrices}', 'grid'),
(1203, 'Semana 7: Registros', 'Structs y arreglos de registros.', '2h', 7, '{Structs, Registros}', 'database'),
(1203, 'Semana 8: Examen Parcial', 'Evaluación parcial.', '2h', 8, '{Examen Parcial}', 'edit'),
(1203, 'Semana 9: Cadenas', 'Manejo de strings.', '2h', 9, '{Strings, Operaciones con texto}', 'type'),
(1203, 'Semana 10: Subprogramas', 'Funciones y procedimientos.', '2h', 10, '{Funciones, Parámetros}', 'box'),
(1203, 'Semana 11: Recursividad', 'Conceptos de recursión.', '2h', 11, '{Recursividad}', 'refresh-cw'),
(1203, 'Semana 12: Archivos', 'Manejo de archivos secuenciales y aleatorios.', '2h', 12, '{Archivos, Lectura/Escritura}', 'save'),
(1203, 'Semana 13: Punteros y Listas', 'Listas enlazadas.', '2h', 13, '{Punteros, Listas enlazadas}', 'link'),
(1203, 'Semana 14: Pilas y Colas', 'Estructuras LIFO y FIFO.', '2h', 14, '{Stacks, Queues}', 'layers'),
(1203, 'Semana 15: Árboles', 'Árboles binarios.', '2h', 15, '{Árboles binarios, Recorridos}', 'git-merge'),
(1203, 'Semana 16: Examen Final', 'Evaluación final.', '2h', 16, '{Examen Final}', 'file-text');
