// Fallback del banco de recursos del dashboard. Es el UNICO export que se
// conserva a proposito: lo usa components/dashboard/recent-resources.tsx
// cuando no hay sesion, la respuesta viene vacia o el backend no responde
// (regla de mantenimiento de mock de AGENTE.md seccion 2).
//
// Eliminados en la Fase 2 de RUTA_DESPLIEGUE_MVP.md por no tener ningun
// consumidor en el codigo fuente: CAREERS, CURRICULUM_DATA,
// LEARNING_PATH_DATA, TIMELINE_DATA, AI_INSIGHTS_DATA, EXAM_BANK_DATA,
// DASHBOARD_STATS y ACHIEVEMENTS.

import type { Recurso } from "@/types/recurso"

export const RECURSOS_DATA: Recurso[] = [
  {
    id: 1,
    titulo: "Estructuras de Datos",
    codigo_curso: "CS201",
    nombre_curso: null,
    tipo: "Examen",
    curso_id: null,
    ciclo: 2,
    facultad_nombre: "Ingeniería",
    year: 2024,
    downloads: 2450,
    rating: 4.8,
    preview_url: null,
    url_drive: null,
    has_solucionario: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 2,
    titulo: "Algoritmos Avanzados",
    codigo_curso: "CS301",
    nombre_curso: null,
    tipo: "Practica",
    curso_id: null,
    ciclo: 3,
    facultad_nombre: "Ingeniería",
    year: 2024,
    downloads: 1890,
    rating: 4.6,
    preview_url: null,
    url_drive: null,
    has_solucionario: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 3,
    titulo: "Cálculo II - Parcial 1",
    codigo_curso: "MAT201",
    nombre_curso: null,
    tipo: "Examen",
    curso_id: null,
    ciclo: 2,
    facultad_nombre: "Ingeniería",
    year: 2024,
    downloads: 3200,
    rating: 4.7,
    preview_url: null,
    url_drive: null,
    has_solucionario: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 4,
    titulo: "Introducción a Bases de Datos",
    codigo_curso: "DB301",
    nombre_curso: null,
    tipo: "Libro",
    curso_id: null,
    ciclo: 3,
    facultad_nombre: "Ingeniería",
    year: 2023,
    downloads: 1450,
    rating: 4.5,
    preview_url: null,
    url_drive: null,
    has_solucionario: false,
    created_at: "2023-01-01T00:00:00Z",
  },
  {
    id: 5,
    titulo: "Apunte de Física I",
    codigo_curso: "FIS101",
    nombre_curso: null,
    tipo: "Apunte",
    curso_id: null,
    ciclo: 1,
    facultad_nombre: "Ingeniería",
    year: 2023,
    downloads: 980,
    rating: 4.3,
    preview_url: null,
    url_drive: null,
    has_solucionario: false,
    created_at: "2023-01-01T00:00:00Z",
  },
  {
    id: 6,
    titulo: "Seguridad Informática - Final",
    codigo_curso: "SEC401",
    nombre_curso: null,
    tipo: "Examen",
    curso_id: null,
    ciclo: 4,
    facultad_nombre: "Ingeniería",
    year: 2023,
    downloads: 756,
    rating: 4.4,
    preview_url: null,
    url_drive: null,
    has_solucionario: true,
    created_at: "2023-01-01T00:00:00Z",
  },
  {
    id: 7,
    titulo: "Física II - Guía de Problemas",
    codigo_curso: "FIS201",
    nombre_curso: null,
    tipo: "Practica",
    curso_id: null,
    ciclo: 2,
    facultad_nombre: "Ingeniería",
    year: 2024,
    downloads: 1123,
    rating: 4.5,
    preview_url: null,
    url_drive: null,
    has_solucionario: false,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 8,
    titulo: "Álgebra Lineal - Apuntes Completos",
    codigo_curso: "ALG101",
    nombre_curso: null,
    tipo: "Apunte",
    curso_id: null,
    ciclo: 2,
    facultad_nombre: "Ingeniería",
    year: 2024,
    downloads: 1567,
    rating: 4.7,
    preview_url: null,
    url_drive: null,
    has_solucionario: false,
    created_at: "2024-01-01T00:00:00Z",
  },
]
