import type { Recurso } from "@/types/recurso"

// CAREER DATA
export const CAREERS = [
  {
    id: "cs",
    name: "Ingeniería en Ciencias de la Computación",
    code: "CS",
    facultad: "Ingeniería",
    description: "Programa de formación en ciencias de la computación",
  },
  {
    id: "ce",
    name: "Ingeniería Civil",
    code: "CE",
    facultad: "Ingeniería",
    description: "Programa de formación en ingeniería civil",
  },
  {
    id: "ee",
    name: "Ingeniería Eléctrica",
    code: "EE",
    facultad: "Ingeniería",
    description: "Programa de formación en ingeniería eléctrica",
  },
  {
    id: "ie",
    name: "Ingeniería Industrial",
    code: "IE",
    facultad: "Ingeniería",
    description: "Programa de formación en ingeniería industrial",
  },
]

// CURRICULUM STRUCTURE (Malla Curricular)
export const CURRICULUM_DATA = [
  {
    ciclo: "Ciclo I",
    credits: 18,
    courses: [
      {
        id: "c101",
        code: "CS101",
        name: "Programación Fundamental",
        credits: 4,
        status: "completed" as const,
        description: "Introducción a los conceptos básicos de programación using Python",
      },
      {
        id: "c102",
        code: "MAT101",
        name: "Cálculo I",
        credits: 4,
        status: "completed" as const,
        description: "Fundamentos de límites, derivadas e integrales",
      },
      {
        id: "c103",
        code: "FIS101",
        name: "Física I",
        credits: 4,
        status: "completed" as const,
        description: "Mecánica clásica y termodinámica básica",
      },
      {
        id: "c104",
        code: "COM101",
        name: "Comunicación",
        credits: 3,
        status: "completed" as const,
        description: "Habilidades de comunicación académica y profesional",
      },
      {
        id: "c105",
        code: "HUM101",
        name: "Humanidades",
        credits: 3,
        status: "completed" as const,
        description: "Introducción a la filosofía y ética",
      },
    ],
  },
  {
    ciclo: "Ciclo II",
    credits: 19,
    courses: [
      {
        id: "c201",
        code: "CS201",
        name: "Estructuras de Datos",
        credits: 4,
        status: "in_progress" as const,
        description: "Listas, pilas, colas, árboles y grafos",
      },
      {
        id: "c202",
        code: "MAT201",
        name: "Cálculo II",
        credits: 4,
        status: "in_progress" as const,
        description: "Integrales múltiples y ecuaciones diferenciales",
      },
      {
        id: "c203",
        code: "FIS201",
        name: "Física II",
        credits: 4,
        status: "in_progress" as const,
        description: "Electricidad y magnetismo",
      },
      {
        id: "c204",
        code: "ALG101",
        name: "Álgebra Lineal",
        credits: 4,
        status: "in_progress" as const,
        description: "Matrices, vectores y transformaciones lineales",
      },
      {
        id: "c205",
        code: "ENG101",
        name: "Inglés Técnico",
        credits: 3,
        status: "in_progress" as const,
        description: "Inglés para programación y documentación técnica",
      },
    ],
  },
  {
    ciclo: "Ciclo III",
    credits: 20,
    courses: [
      {
        id: "c301",
        code: "CS301",
        name: "Algoritmos",
        credits: 4,
        status: "available" as const,
        description: "Análisis y diseño de algoritmos eficientes",
      },
      {
        id: "c302",
        code: "DB301",
        name: "Bases de Datos",
        credits: 4,
        status: "available" as const,
        description: "Modelado relacional, SQL y diseño de esquemas",
      },
      {
        id: "c303",
        code: "SYS301",
        name: "Sistemas Operativos",
        credits: 4,
        status: "available" as const,
        description: "Procesos, memoria, entrada/salida y gestión de recursos",
      },
      {
        id: "c304",
        code: "STA301",
        name: "Estadística",
        credits: 4,
        status: "available" as const,
        description: "Probabilidad, distribuciones e inferencia estadística",
      },
      {
        id: "c305",
        code: "PRJ301",
        name: "Proyecto I",
        credits: 4,
        status: "available" as const,
        description: "Proyecto práctico integrando conocimientos del ciclo",
      },
    ],
  },
  {
    ciclo: "Ciclo IV",
    credits: 20,
    courses: [
      {
        id: "c401",
        code: "WEB401",
        name: "Desarrollo Web",
        credits: 4,
        status: "locked" as const,
        description: "Frontend y backend con frameworks modernos",
      },
      {
        id: "c402",
        code: "MOB401",
        name: "Desarrollo Móvil",
        credits: 4,
        status: "locked" as const,
        description: "Aplicaciones para iOS y Android",
      },
      {
        id: "c403",
        code: "ML401",
        name: "Machine Learning",
        credits: 4,
        status: "locked" as const,
        description: "Algoritmos de aprendizaje automático y deep learning",
      },
      {
        id: "c404",
        code: "SEC401",
        name: "Seguridad Informática",
        credits: 4,
        status: "locked" as const,
        description: "Criptografía, auditoría y seguridad en redes",
      },
      {
        id: "c405",
        code: "PRJ401",
        name: "Proyecto II",
        credits: 4,
        status: "locked" as const,
        description: "Proyecto capstone integrando especializaciones",
      },
    ],
  },
]

// LEARNING PATH DATA FOR EACH COURSE
export const LEARNING_PATH_DATA: Record<string, any> = {
  c201: {
    code: "CS201",
    name: "Estructuras de Datos",
    professor: "Dr. Carlos Mendez",
    description: "Fundamentos de estructuras de datos: listas, pilas, colas, árboles y grafos",
    credits: 4,
    progress: 45,
    startDate: "2024-01-15",
    endDate: "2024-05-30",
  },
  c101: {
    code: "CS101",
    name: "Programación I",
    professor: "Mg. Ana García",
    description: "Introducción a los conceptos básicos de programación",
    credits: 4,
    progress: 100,
    startDate: "2023-08-01",
    endDate: "2023-12-20",
  },
  c202: {
    code: "MAT201",
    name: "Cálculo II",
    professor: "Dr. Roberto Fernández",
    description: "Integrales múltiples y ecuaciones diferenciales",
    credits: 4,
    progress: 65,
    startDate: "2024-01-15",
    endDate: "2024-05-30",
  },
}

// TIMELINE STEPS FOR LEARNING PATHS
export const TIMELINE_DATA: Record<string, any> = {
  c201: [
    {
      id: "step1",
      title: "Introducción a Estructuras de Datos",
      description: "Conceptos fundamentales y clasificación de estructuras de datos",
      duration: "1 semana",
      status: "completed",
      topics: ["Arrays", "Linked Lists", "Memory Management"],
      icon: "BookOpen",
      resources: [
        { type: "video", title: "Introducción a ED", duration: "15 min" },
        { type: "document", title: "Guía de Conceptos Fundamentales" },
      ],
    },
    {
      id: "step2",
      title: "Arrays y Listas Dinámicas",
      description: "Implementación y operaciones en arrays y listas enlazadas",
      duration: "2 semanas",
      status: "current",
      topics: ["Array Operations", "Linked Lists Implementation", "Dynamic Memory"],
      icon: "Code",
      resources: [
        { type: "video", title: "Arrays en Profundidad", duration: "22 min" },
        { type: "code", title: "Ejemplos de Código - Arrays" },
        { type: "document", title: "Ejercicios Prácticos" },
      ],
    },
    {
      id: "step3",
      title: "Pilas y Colas",
      description: "Estructuras LIFO y FIFO con aplicaciones prácticas",
      duration: "2 semanas",
      status: "upcoming",
      topics: ["Stack Implementation", "Queue Implementation", "Applications"],
      icon: "Circle",
      resources: [
        { type: "video", title: "Pilas y Colas", duration: "18 min" },
        { type: "code", title: "Implementaciones" },
      ],
    },
    {
      id: "step4",
      title: "Árboles Binarios",
      description: "Estructuras jerárquicas y algoritmos de búsqueda en árboles",
      duration: "3 semanas",
      status: "upcoming",
      topics: ["Binary Trees", "Tree Traversal", "BST Operations"],
      icon: "Circle",
      resources: [
        { type: "video", title: "Árboles Binarios", duration: "25 min" },
        { type: "code", title: "Implementación de BST" },
      ],
    },
    {
      id: "step5",
      title: "Grafos y Algoritmos de Búsqueda",
      description: "Representación de grafos y algoritmos BFS, DFS",
      duration: "2 semanas",
      status: "locked",
      topics: ["Graph Representation", "BFS/DFS", "Shortest Path"],
      icon: "Lock",
      resources: [
        { type: "video", title: "Grafos", duration: "28 min" },
        { type: "code", title: "Algoritmos de Grafos" },
      ],
    },
  ],
}

// AI INSIGHTS FOR LEARNING PATHS
export const AI_INSIGHTS_DATA: Record<string, any> = {
  c201: [
    {
      type: "strength",
      title: "Dominio de Conceptos Básicos",
      description: "Tu desempeño en arrays y operaciones fundamentales es excelente (92% de precisión)",
      impact: "+15% en pruebas",
      action: "Ver análisis detallado",
    },
    {
      type: "weakness",
      title: "Complejidad Temporal",
      description: "Necesitas reforzar tu comprensión del análisis Big O y optimización de algoritmos",
      impact: "-8% en eficiencia",
      action: "Practicar problemas de complejidad",
    },
    {
      type: "recommendation",
      title: "Próximo Paso Recomendado",
      description:
        "Basado en tu ritmo de aprendizaje, acelera el estudio de Pilas y Colas. Completar 5 ejercicios adicionales te preparará para Árboles",
      impact: "Ahorra 1 semana",
      action: "Ver ejercicios",
    },
    {
      type: "opportunity",
      title: "Oportunidad de Aprendizaje",
      description:
        "Explorar aplicaciones prácticas de colas en sistemas de simulación puede mejorar tu comprensión conceptual",
      impact: "+25% en retención",
      action: "Ver proyectos",
    },
  ],
}

// EXAM BANK DATA FOR COURSES
export const EXAM_BANK_DATA: Record<string, any> = {
  c201: [
    {
      id: "exam1",
      title: "Examen Parcial - Ciclo II 2024",
      type: "midterm",
      year: 2024,
      difficulty: "hard",
      questions: 45,
      duration: 120,
      downloads: 342,
      hasAnswers: true,
    },
    {
      id: "exam2",
      title: "Examen Parcial - Ciclo II 2023",
      type: "midterm",
      year: 2023,
      difficulty: "medium",
      questions: 40,
      duration: 120,
      downloads: 521,
      hasAnswers: true,
    },
    {
      id: "exam3",
      title: "Examen Final - Ciclo II 2024",
      type: "final",
      year: 2024,
      difficulty: "hard",
      questions: 60,
      duration: 180,
      downloads: 289,
      hasAnswers: true,
    },
    {
      id: "exam4",
      title: "Examen Final - Ciclo II 2023",
      type: "final",
      year: 2023,
      difficulty: "medium",
      questions: 58,
      duration: 180,
      downloads: 412,
      hasAnswers: true,
    },
    {
      id: "exam5",
      title: "Quiz 1 - Introducción a ED",
      type: "quiz",
      year: 2024,
      difficulty: "easy",
      questions: 15,
      duration: 30,
      downloads: 156,
      hasAnswers: true,
    },
    {
      id: "exam6",
      title: "Problemas de Práctica - Semana 3",
      type: "practice",
      year: 2024,
      difficulty: "medium",
      questions: 20,
      duration: 90,
      downloads: 234,
      hasAnswers: false,
    },
  ],
}

// RESOURCES FOR BIBLIOTECA CENTRAL
export const RECURSOS_DATA: Recurso[] = [
  {
    id: "1",
    title: "Estructuras de Datos",
    code: "CS201",
    semester: "2024-II",
    type: "Examen",
    ciclo: 2,
    facultad: "Ingeniería",
    year: 2024,
    downloads: 2450,
    rating: 4.8,
    preview: true,
    hasSolucionario: true,
  },
  {
    id: "2",
    title: "Algoritmos Avanzados",
    code: "CS301",
    semester: "2024-II",
    type: "Práctica",
    ciclo: 3,
    facultad: "Ingeniería",
    year: 2024,
    downloads: 1890,
    rating: 4.6,
    preview: true,
    hasSolucionario: true,
  },
  {
    id: "3",
    title: "Cálculo II - Parcial 1",
    code: "MAT201",
    semester: "2024-I",
    type: "Examen",
    ciclo: 2,
    facultad: "Ingeniería",
    year: 2024,
    downloads: 3200,
    rating: 4.7,
    preview: true,
    hasSolucionario: true,
  },
  {
    id: "4",
    title: "Introducción a Bases de Datos",
    code: "DB301",
    semester: "2024-II",
    type: "Libro",
    ciclo: 3,
    facultad: "Ingeniería",
    year: 2023,
    downloads: 1450,
    rating: 4.5,
    preview: true,
    hasSolucionario: false,
  },
  {
    id: "5",
    title: "Apunte de Física I",
    code: "FIS101",
    semester: "2024-I",
    type: "Apunte",
    ciclo: 1,
    facultad: "Ingeniería",
    year: 2023,
    downloads: 980,
    rating: 4.3,
    preview: true,
    hasSolucionario: false,
  },
  {
    id: "6",
    title: "Seguridad Informática - Final",
    code: "SEC401",
    semester: "2024-I",
    type: "Examen",
    ciclo: 4,
    facultad: "Ingeniería",
    year: 2023,
    downloads: 756,
    rating: 4.4,
    preview: true,
    hasSolucionario: true,
  },
  {
    id: "7",
    title: "Física II - Guía de Problemas",
    code: "FIS201",
    semester: "2024-II",
    type: "Práctica",
    ciclo: 2,
    facultad: "Ingeniería",
    year: 2024,
    downloads: 1123,
    rating: 4.5,
    preview: true,
    hasSolucionario: false,
  },
  {
    id: "8",
    title: "Álgebra Lineal - Apuntes Completos",
    code: "ALG101",
    semester: "2024-II",
    type: "Apunte",
    ciclo: 2,
    facultad: "Ingeniería",
    year: 2024,
    downloads: 1567,
    rating: 4.7,
    preview: true,
    hasSolucionario: false,
  },
]

// DASHBOARD STATS
export const DASHBOARD_STATS = {
  activeCourses: 5,
  semesterProgress: 68,
  masterSkills: 12,
}

// ACHIEVEMENTS/LOGROS
export const ACHIEVEMENTS = [
  {
    id: "1",
    name: "Primer Paso",
    description: "Completar el primer curso",
    icon: "🎓",
    unlockedAt: "2024-01-15",
  },
  {
    id: "2",
    name: "Ritmo Acelerado",
    description: "Aprobar 3 cursos en un ciclo",
    icon: "⚡",
    unlockedAt: "2024-03-20",
  },
  {
    id: "3",
    name: "Dedicación Premium",
    description: "Completar 90 horas de estudio",
    icon: "🏆",
    unlockedAt: null,
  },
  {
    id: "4",
    name: "Perfeccionista",
    description: "Obtener nota perfecto en 2 exámenes",
    icon: "⭐",
    unlockedAt: null,
  },
  {
    id: "5",
    name: "Experto en Datos",
    description: "Completar todos los cursos de Data Science",
    icon: "📊",
    unlockedAt: null,
  },
]
